# Generated by Django 4.2 on 2023-05-24 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_user_birthdate_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="login",
            new_name="username",
        ),
    ]
