# Generated by Django 4.2 on 2023-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0003_program_exercises"),
        ("authentication", "0009_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="programs",
            field=models.ManyToManyField(
                related_name="programs", to="program.program", verbose_name="Программы"
            ),
        ),
    ]
