# Generated by Django 4.2 on 2023-05-30 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0011_alter_user_programs"),
    ]

    operations = []
