version: "3.9"

services:
  api:
    build:
      context: /api/
      dockerfile: ./Dockerfile
    volumes:
      - ./api/static:/api/static
      - ./api/media:/api/media
    networks:
      - myNetwork
    ports:
      - 8000:8000
    restart: always
  app:
    build:
      context: /app/
      dockerfile: ./Dockerfile
    networks:
      - myNetwork
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - api

networks:
  myNetwork:
    driver: bridge
